# Generated by Django 5.0.4 on 2024-04-07 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration_model',
            fields=[
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('points', models.IntegerField(default=0)),
                ('referral_code', models.CharField(default=None, max_length=20)),
                ('unique_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
            ],
        ),
    ]
