# Generated by Django 5.0.4 on 2024-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration_model',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
