# Generated by Django 5.0.4 on 2024-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0002_alter_user_registration_model_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration_model',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
