# Generated by Django 5.0.4 on 2024-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_alter_user_registration_model_unique_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_registration_model',
            new_name='UserRegistrationModel',
        ),
    ]
