# Generated by Django 5.0.4 on 2024-04-07 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0005_rename_user_registration_model_userregistrationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 18, 6, 37, 245629)),
        ),
    ]
